plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs

packageExtensions:
  'apollo-engine-reporting-protobuf@*': # See https://github.com/apollographql/apollo-server/issues/3574
    dependencies:
      'long': '*'
  'apollo-reporting-protobuf@*':
    dependencies:
      'long': '*'
  '@nestjs/graphql@*':
    dependencies:
      'apollo-env': '*'
  '@oclif/plugin-help@*':
    dependencies:
      '@oclif/errors': '*'
